# Generated by Django 5.1.6 on 2025-05-23 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='date_of_brith',
            new_name='date_of_birth',
        ),
    ]
