# Generated by Django 5.2.1 on 2025-06-11 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_feed', '0017_alter_news_body_alter_news_body_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='language',
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='news/images'),
        ),
    ]
